
sourcedir: "/net/snowwhite/home/jedidiah/"
outdir: "/net/snowwhite/home/jedidiah/topmed_freeze5_dnms/merged/anno/"
vcfdir: "/net/snowwhite/home/jedidiah/topmed_freeze5_dnms/merged/"

pythonpath: "/net/snowwhite/home/jedidiah/anaconda3/envs/anno/bin/python"
bcftoolspath: "/net/snowwhite/home/jedidiah/anaconda3/envs/anno/bin/bcftools"

grch37: "/net/snowwhite/home/jedidiah/GRCh37-lite.fa"
grch38: "/net/topmed/working/mapping/gotcloud/ref/hg38/hs38DH.fa"

freeze5_ancestry: "/net/topmed2/working/klemmerr/global_list_b38all.txt"
freeze5_ped_related: "/net/topmed8/working/call_sets/out.2017_05/index/freeze5.64960.4606.ped"